---

name: Typos

# yamllint disable-line rule:truthy
on: [push, pull_request, workflow_dispatch]

jobs:
  Typos:
    # Copied from: https://github.com/junegunn/fzf/blob/master/
    # -- .github/workflows/typos.yml
    name: Typos
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: crate-ci/typos@v1.13.16
